name: caddy-alpine

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  DOCKER_REPO_NAME: rookiezoe/caddy

jobs:
  get_env:
    runs-on: ubuntu-latest
    outputs:
      LATEST_TAG: ${{ steps.set_outputs.outputs.LATEST_TAG }}
      CADDY_VERSION: ${{ steps.set_outputs.outputs.CADDY_VERSION }}
    steps:
      - id: set_outputs
        env:
          DEBIAN_FRONTEND: noninteractive
        name: Set outputs
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install jq
          export QUREY_PARAMS="?page_size=2&page=1&ordering=last_updated"
          export LATEST_TAG=$(echo -n $(curl -s "https://hub.docker.com/v2/repositories/${DOCKER_REPO_NAME}/tags/${QUREY_PARAMS}" | jq -r '.results | sort_by(.name) | first | .name'))
          export CADDY_VERSION=$(echo -n $(curl -s https://api.github.com/repos/caddyserver/caddy/releases | jq -r 'sort_by(.published_at) | last | .tag_name' | awk -Fv '{print $2}'))
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "CADDY_VERSION=$CADDY_VERSION" >> $GITHUB_OUTPUT

  docker:
    if: needs.get_env.outputs.LATEST_TAG != needs.get_env.outputs.CADDY_VERSION
    runs-on: ubuntu-latest
    needs: get_env
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REPO_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ needs.get_env.outputs.CADDY_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./caddy
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CADDY_VERSION=${{ needs.get_env.outputs.CADDY_VERSION }}
