name: rsshub-alpine
on:
  workflow_dispatch:
  repository_dispatch:
    types: 'build-rsshub'

env:
  DOCKER_REPO_NAME: rookiezoe/rsshub

jobs:
  get_env:
    runs-on: ubuntu-latest
    outputs:
      LATEST_TAG: ${{ steps.set_outputs.outputs.LATEST_TAG }}
      RSSHUB_VERSION: ${{ steps.set_outputs.outputs.RSSHUB_VERSION }}
    steps:
      - id: set_outputs
        env:
          DEBIAN_FRONTEND: noninteractive
        name: Set outputs
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install jq
          export QUREY_PARAMS="?page_size=2&page=1&ordering=last_updated"
          export LATEST_TAG=$(echo -n $(curl -s "https://hub.docker.com/v2/repositories/${DOCKER_REPO_NAME}/tags/${QUREY_PARAMS}" | jq -r '.results | sort_by(.name) | first | .name'))
          export RSSHUB_VERSION=$(echo -n $(date -d@$(curl -u $GITHUB_USERNAME:$GITHUB_TOKEN -s 'https://api.github.com/repos/DIYgod/RSSHub/commits?sha=master' | jq -r 'sort_by(.commit.author.date) | last | .commit.author.date | fromdate') +'%y.%m.%d'))
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "RSSHUB_VERSION=$RSSHUB_VERSION" >> $GITHUB_OUTPUT

  publish:
    if: needs.get_env.outputs.LATEST_TAG != needs.get_env.outputs.RSSHUB_VERSION
    runs-on: ubuntu-latest
    needs: get_env
    steps:
      - uses: actions/checkout@v2
      - name: checkout rsshub
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git
          git clone -b master --single-branch https://github.com/DIYgod/RSSHub.git $GITHUB_WORKSPACE/rsshub/RSSHub
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_REPO_NAME }}:latest,${{ env.DOCKER_REPO_NAME }}:${{ needs.get_env.outputs.RSSHUB_VERSION }}
          context: ./rsshub
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            RSSHub=RSSHub
