name: rsshub-alpine
on:
  schedule:
    - cron: '0 2 28 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rookiezoe/rsshub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./rsshub/Dockerfile
      - name: Publish to docker.pkg.github.com
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/rookiezoe/containers/rsshub
          username: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
          dockerfile: ./rsshub/Dockerfile
          registry: docker.pkg.github.com
