name: rsshub-alpine
on:
  schedule:
    - cron: '0 0 5/15 * *'
  repository_dispatch:
    types: 'build-rsshub'

env:
  DOCKER_REPO_NAME: rookiezoe/rsshub

jobs:
  get_env:
    runs-on: ubuntu-latest
    outputs:
      LATEST_TAG: ${{ steps.set_outputs.outputs.LATEST_TAG }}
      LATEST_COMMIT: ${{ steps.set_outputs.outputs.LATEST_COMMIT }}
    steps:
      - id: set_outputs
        env:
          DEBIAN_FRONTEND: noninteractive
        name: Set outputs
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install jq
          export LATEST_TAG=$(echo -n $(curl -s "https://registry.hub.docker.com/v1/repositories/${DOCKER_REPO_NAME}/tags" | jq -r 'sort_by(.name) | reverse | .[1].name'))
          export LATEST_COMMIT_DATETIME=$(echo -n $(curl -u $GITHUB_USERNAME:$GITHUB_TOKEN -s https://api.github.com/repos/DIYgod/RSSHub/commits | jq -r 'sort_by(.commit.author.date) | last | .commit.author.date | fromdate'))
          export LATEST_COMMIT="commit-$LATEST_COMMIT_DATETIME"
          echo ::set-output name=LATEST_TAG::$LATEST_TAG
          echo ::set-output name=LATEST_COMMIT::$LATEST_COMMIT

  publish:
    if: needs.get_env.outputs.LATEST_TAG != needs.get_env.outputs.LATEST_COMMIT
    runs-on: ubuntu-latest
    needs: get_env
    steps:
      - uses: actions/checkout@master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: latest,${{ needs.get_env.outputs.LATEST_COMMIT }}
          context: ./rsshub
